/*
 * Copyright 2025 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package agentic

import (
	"github.com/cloudwego/eino/callbacks"
	"github.com/cloudwego/eino/schema"
)

// TokenUsageMeta is the token usage for the model.
type TokenUsageMeta struct {
	InputTokens         int64                    `json:"input_tokens"`
	InputTokensDetails  InputTokensUsageDetails  `json:"input_tokens_details"`
	OutputTokens        int64                    `json:"output_tokens"`
	OutputTokensDetails OutputTokensUsageDetails `json:"output_tokens_details"`
	TotalTokens         int64                    `json:"total_tokens"`
}

type InputTokensUsageDetails struct {
	CachedTokens int64 `json:"cached_tokens"`
}

type OutputTokensUsageDetails struct {
	ReasoningTokens int64 `json:"reasoning_tokens"`
}

// Config is the config for the model.
type Config struct {
	// Model is the model name.
	Model string
	// Temperature is the temperature, which controls the randomness of the model.
	Temperature float32
	// TopP is the top p, which controls the diversity of the model.
	TopP float32
}

// CallbackInput is the input for the model callback.
type CallbackInput struct {
	// Responses is the responses to be sent to the model.
	Responses []*schema.AgenticMessage
	// Tools is the tools to be used in the model.
	Tools []*schema.ToolInfo
	// Config is the config for the model.
	Config *Config
	// Extra is the extra information for the callback.
	Extra map[string]any
}

// CallbackOutput is the output for the model callback.
type CallbackOutput struct {
	// Response is the response generated by the model.
	Response *schema.AgenticMessage
	// Config is the config for the model.
	Config *Config
	// Usage is the token usage of this request.
	Usage *TokenUsageMeta
	// Extra is the extra information for the callback.
	Extra map[string]any
}

// ConvCallbackInput converts the callback input to the model callback input.
func ConvCallbackInput(src callbacks.CallbackInput) *CallbackInput {
	switch t := src.(type) {
	case *CallbackInput: // when callback is triggered within component implementation, the input is usually already a typed *model.CallbackInput
		return t
	case []*schema.AgenticMessage: // when callback is injected by graph node, not the component implementation itself, the input is the input of Chat Model interface, which is []*schema.AgenticMessage
		return &CallbackInput{
			Responses: t,
		}
	default:
		return nil
	}
}

// ConvCallbackOutput converts the callback output to the model callback output.
func ConvCallbackOutput(src callbacks.CallbackOutput) *CallbackOutput {
	switch t := src.(type) {
	case *CallbackOutput: // when callback is triggered within component implementation, the output is usually already a typed *model.CallbackOutput
		return t
	case *schema.AgenticMessage: // when callback is injected by graph node, not the component implementation itself, the output is the output of Chat Model interface, which is *schema.AgenticMessage
		return &CallbackOutput{
			Response: t,
		}
	default:
		return nil
	}
}
