/*
 * Copyright 2025 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package taskstate provides task lifecycle management infrastructure for background tasks.
// It defines a Manager interface for registering, tracking, and controlling the lifecycle
// of background tasks (e.g., sub-agent executions, shell commands).
//
// The Manager is designed to be independent of specific execution engines — the same Manager
// can track sub-agent tasks, background shell commands, or any other async work.
// Users create a Manager per session and inject it into middlewares that need background
// task support.
package taskstate

import (
	"context"
	"time"

	"github.com/cloudwego/eino/adk"
	"github.com/cloudwego/eino/components/tool"
)

// Status represents the lifecycle status of a background task.
type Status string

const (
	// StatusRunning indicates the task is currently executing.
	StatusRunning Status = "running"
	// StatusCompleted indicates the task finished successfully.
	StatusCompleted Status = "completed"
	// StatusFailed indicates the task terminated with an error.
	StatusFailed Status = "failed"
	// StatusCancelled indicates the task was cancelled by an external request.
	StatusCancelled Status = "cancelled"
)

// Entry contains the metadata and current state of a task.
// All fields are safe to read after obtaining from Manager.Get or Manager.List.
type Entry struct {
	// ID is the unique identifier for this task, generated by the Manager.
	ID string
	// Description is a human-readable summary of what the task does.
	Description string
	// Status is the current lifecycle status.
	Status Status
	// Result contains the task output, set when Status is StatusCompleted.
	Result string
	// Error contains the error message, set when Status is StatusFailed.
	Error string
	// CreatedAt is the time the task was registered.
	CreatedAt time.Time
	// DoneAt is the time the task reached a terminal state. Nil if still running.
	DoneAt *time.Time
}

// Notification is emitted when a task reaches a terminal state (completed, failed, or cancelled).
type Notification struct {
	// Entry contains the final state of the task.
	Entry *Entry
}

// RegisterInfo contains the information needed to register a new task.
type RegisterInfo struct {
	// Description is a human-readable summary of what the task does.
	Description string
}

// Handle is returned from Manager.Register and provides the task owner with the ability
// to signal completion or failure, and to receive intermediate events.
type Handle struct {
	// ID is the unique identifier for this task.
	ID string

	// Complete marks the task as successfully completed with the given result.
	// This function is idempotent — only the first call takes effect.
	Complete func(result string)

	// Fail marks the task as failed with the given error.
	// This function is idempotent — only the first call takes effect.
	Fail func(err error)

	// OnEvent is an optional callback for intermediate events from the task executor.
	// The Manager implementation injects this at Register time based on its configuration.
	// If nil, intermediate events are discarded.
	// The event parameter is intentionally typed as `any` so that the Manager remains
	// independent of specific event types (e.g., AgentEvent, BashEvent).
	OnEvent func(event any)

	// Ctx is a context scoped to this task's lifetime.
	// It is cancelled when Cancel(id) is called on the Manager, or when the Manager is closed.
	// Task executors should use this context for their work to enable graceful cancellation.
	Ctx context.Context
}

// Manager manages the lifecycle of background tasks.
//
// It is designed to be created per session and shared across middlewares that need
// background task support. The Manager is independent of specific execution engines —
// any middleware can Register tasks and use the returned Handle to signal completion.
//
// Typical usage:
//
//	mgr := taskstate.NewInMemoryManager()
//	defer mgr.Close(context.Background())
//
//	// Inject into middlewares
//	subagentMW := subagent.New(ctx, &subagent.Config{
//	    SubAgents:    agents,
//	    TaskStateMgr: mgr,
//	})
//
//	// After agent run, drain background task notifications
//	for mgr.HasRunning() {
//	    notification := <-mgr.Notifications()
//	    // process notification, trigger new agent run, etc.
//	}
type Manager interface {
	// Register creates a new task in StatusRunning and returns a Handle for the task owner.
	// The returned Handle.Ctx is derived from the provided ctx and will be cancelled
	// when Cancel is called or the Manager is closed.
	Register(ctx context.Context, info *RegisterInfo) (*Handle, error)

	// Get returns the current state of a task by ID.
	// Returns (nil, false) if the task does not exist.
	Get(id string) (*Entry, bool)

	// List returns a snapshot of all tasks (both running and completed).
	List() []*Entry

	// Cancel requests cancellation of a running task.
	// The task's Handle.Ctx will be cancelled, and the task will transition to StatusCancelled.
	// Returns an error if the task does not exist or is not in StatusRunning.
	Cancel(id string) error

	// Notifications returns a read-only channel that receives a Notification
	// each time a task reaches a terminal state (completed, failed, or cancelled).
	Notifications() <-chan *Notification

	// HasRunning reports whether any tasks are currently in StatusRunning.
	HasRunning() bool

	// WaitAllDone blocks until all registered tasks have reached a terminal state,
	// or until the provided context is cancelled.
	WaitAllDone(ctx context.Context) error

	// Close performs graceful shutdown of the Manager.
	// It waits for all running tasks to complete (up to the ctx deadline),
	// then cancels any remaining running tasks and closes the Notifications channel.
	// After Close returns, Register will return an error.
	Close(ctx context.Context) error
}

type TaskInfo struct {
	SubagentType    string `json:"subagent_type"`
	Description     string `json:"description"`
	RunInBackground *bool  `json:"run_in_background,omitempty"`
}

type ManagerV2 interface {

	// Agent 用不到的， Task Center 进行任务管理的， 主要是实例退出时的 Checkpoint & 实例启动时的 Resume(与状态更新的下行通道解耦)
	// 在 SSE 请求的模式下，释放 Handler 之前，必须要清空 TaskState.
	// 在 agent.Run 场景下，无 message query，不可能有消息的优先级队列
	// 所以这个 TaskManger 只能按照 agent.Run 粒度进行设计
	List(ctx context.Context) ([]*Entry, error)
	Cancel(ctx context.Context, agentID string) error
	Resume(ctx context.Context, info *adk.ResumeInfo) (result string, err error)

	// Agent 涉及到的
	Create(ctx context.Context, ti *TaskInfo) (agentID string, err error)
	Exec(ctx context.Context, agentID string, prompt string, opts ...tool.Option) (result string, err error)
	NotificationFrom(ctx context.Context, agentID string) <-chan *Notification
}
