/*
 * Copyright 2026 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package subagent

import (
	"context"
	"fmt"
	"strconv"
	"sync"
	"time"

	"github.com/bytedance/sonic"

	"github.com/cloudwego/eino/adk"
	"github.com/cloudwego/eino/components/tool"
)

// Status represents the lifecycle status of a task.
type Status string

const (
	// StatusRunning indicates the task is currently executing.
	StatusRunning Status = "running"
	// StatusCompleted indicates the task finished successfully.
	StatusCompleted Status = "completed"
	// StatusFailed indicates the task terminated with an error.
	StatusFailed Status = "failed"
	// StatusCanceled indicates the task was canceled by an external request.
	StatusCanceled Status = "canceled"
)

// Task represents a single agent execution record.
type Task struct {
	// ID is the unique identifier for this task, generated by TaskMgr.
	ID string
	// Description is a human-readable summary of what the task does.
	Description string
	// Status is the current lifecycle status.
	Status Status
	// Result contains the task output, set when Status is StatusCompleted.
	Result string
	// Error contains the error message, set when Status is StatusFailed.
	Error string
	// RunInBackground indicates whether this task was launched in background mode.
	// This helps distinguish background tasks from foreground ones
	// when inspecting task state after WaitAllDone.
	RunInBackground bool
	// ResultQueried indicates whether the main agent has queried this task's result
	// via the TaskOutput tool. This helps developers know which background task
	// results have already been consumed by the orchestrating agent.
	ResultQueried bool
	// CreatedAt is the time the task was registered.
	CreatedAt time.Time
	// DoneAt is the time the task reached a terminal state. Nil if still running.
	DoneAt *time.Time
	// Metadata holds extensible fields (e.g., InterruptState for future resume support).
	Metadata map[string]any
}

// Notification is emitted when a task reaches a terminal state (completed, failed, or canceled).
type Notification struct {
	// Task contains the final state of the task.
	Task *Task
}

// RunResult is the return value of TaskMgr.Run.
// The caller sees what happened without needing to manage internal handles.
type RunResult struct {
	// TaskID is the unique identifier assigned to this execution.
	TaskID string
	// Status indicates the outcome: StatusCompleted, StatusFailed, or StatusRunning (for background tasks).
	Status Status
	// Result is the agent's output when Status is StatusCompleted.
	Result string
	// Error is the error message when Status is StatusFailed.
	Error string
}

// RunInput is the input for TaskMgr.Run.
// Using a struct instead of positional arguments for extensibility (e.g., future interrupt/resume fields).
type RunInput struct {
	// SubagentType is the name of the registered agent to execute.
	SubagentType string
	// Prompt is the task content passed to the agent as its input.
	Prompt string
	// Description is a short human-readable title for the task, stored in Task.Description.
	Description string
	// RunInBackground controls execution mode: true returns immediately with StatusRunning.
	RunInBackground bool
}

// TaskMgrOption configures a TaskMgr.
type TaskMgrOption func(*TaskMgr)

// WithAutoBackground enables automatic foreground-to-background switching.
// When ms > 0, a foreground agent run that hasn't completed within this many
// milliseconds will automatically switch to background mode.
func WithAutoBackground(ms int) TaskMgrOption {
	return func(m *TaskMgr) {
		m.autoBackgroundMs = ms
	}
}

// NewTaskMgr creates a new TaskMgr for managing sub-agent task lifecycles.
func NewTaskMgr(opts ...TaskMgrOption) *TaskMgr {
	m := &TaskMgr{
		tasks:         make(map[string]*taskRecord),
		notifications: make(chan *Notification, 256),
	}
	m.cond = sync.NewCond(&m.mu)
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// TaskMgr manages the lifecycle of sub-agent executions.
// It owns both the execution (Run) and the state tracking (Get/List/Cancel).
//
// TaskMgr is Agent-aware: it maintains a registry of agents (via RegisterAgent),
// resolves them by name in Run, and manages foreground/background/auto-background
// switching internally. Future interrupt/resume support will also live here.
type TaskMgr struct {
	mu               sync.Mutex
	cond             *sync.Cond
	tasks            map[string]*taskRecord
	agents           map[string]adk.Agent // agent registry: name → Agent
	seq              int64
	notifications    chan *Notification
	closed           bool
	autoBackgroundMs int
}

type taskRecord struct {
	task   Task
	cancel context.CancelFunc
	done   bool // guards complete/fail idempotency
}

// runResult carries the result from a goroutine running the sub-agent.
type runResult struct {
	result string
	err    error
}

// RegisterAgent adds an agent to the TaskMgr registry.
// Agents must be registered before they can be referenced by SubagentType in RunInput.
// Typically called during middleware initialization.
func (m *TaskMgr) RegisterAgent(name string, agent adk.Agent) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if m.agents == nil {
		m.agents = make(map[string]adk.Agent)
	}
	m.agents[name] = agent
}

// Run executes a registered agent as a managed task.
//
// The agent is resolved by input.SubagentType from the internal registry (see RegisterAgent).
// The execution mode depends on input.Background and TaskMgr configuration:
//   - Foreground (RunInBackground=false, autoBackgroundMs=0): blocks until completion
//   - Background (RunInBackground=true): returns immediately with StatusRunning
//   - AutoBackground (autoBackgroundMs>0): foreground with timeout, auto-switches to background
//
// All runs are tracked in TaskMgr state and visible via Get/List/Notifications.
func (m *TaskMgr) Run(ctx context.Context, input *RunInput, opts ...tool.Option) (*RunResult, error) {
	agent, ok := m.getAgent(input.SubagentType)
	if !ok {
		return nil, fmt.Errorf("subagent: agent %q not registered in TaskMgr", input.SubagentType)
	}

	id, taskCtx, err := m.register(ctx, input.Description, input.RunInBackground)
	if err != nil {
		return nil, err
	}

	// Build the request params for the agent tool wrapper.
	params, err := sonic.MarshalString(map[string]string{
		"request": input.Prompt,
	})
	if err != nil {
		m.fail(id, err)
		return nil, fmt.Errorf("subagent: failed to marshal agent params: %w", err)
	}

	// Wrap the Agent as an InvokableTool for execution.
	bt := adk.NewAgentTool(ctx, agent)
	invokable, invokableOK := bt.(tool.InvokableTool)
	if !invokableOK {
		m.fail(id, fmt.Errorf("agent %q does not implement InvokableTool", input.SubagentType))
		return nil, fmt.Errorf("subagent: agent %q does not implement InvokableTool", input.SubagentType)
	}

	resultCh := make(chan runResult, 1)
	go func() {
		r, runErr := invokable.InvokableRun(taskCtx, params, opts...)
		if runErr != nil {
			m.fail(id, runErr)
		} else {
			m.complete(id, r)
		}
		resultCh <- runResult{r, runErr}
	}()

	// Explicit background: return immediately.
	if input.RunInBackground {
		return &RunResult{TaskID: id, Status: StatusRunning}, nil
	}

	// Auto-background: wait with timeout, then switch to background.
	if m.autoBackgroundMs > 0 {
		select {
		case r := <-resultCh:
			return m.toRunResult(id, r), nil
		case <-time.After(time.Duration(m.autoBackgroundMs) * time.Millisecond):
			return &RunResult{TaskID: id, Status: StatusRunning}, nil
		}
	}

	// Foreground: block until completion.
	r := <-resultCh
	return m.toRunResult(id, r), nil
}

func (m *TaskMgr) toRunResult(id string, r runResult) *RunResult {
	if r.err != nil {
		return &RunResult{TaskID: id, Status: StatusFailed, Error: r.err.Error()}
	}
	return &RunResult{TaskID: id, Status: StatusCompleted, Result: r.result}
}

// Get returns the current state of a task by ID.
// Returns (nil, false) if the task does not exist.
func (m *TaskMgr) Get(id string) (*Task, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok {
		return nil, false
	}
	clone := rec.task
	return &clone, true
}

// MarkQueried marks a task's result as having been queried by the main agent
// (typically via the TaskOutput tool). This helps developers know which
// background task results the orchestrating agent has already consumed.
func (m *TaskMgr) MarkQueried(id string) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if rec, ok := m.tasks[id]; ok {
		rec.task.ResultQueried = true
	}
}

// List returns a snapshot of all tasks (both running and completed).
func (m *TaskMgr) List() []*Task {
	m.mu.Lock()
	defer m.mu.Unlock()

	tasks := make([]*Task, 0, len(m.tasks))
	for _, rec := range m.tasks {
		clone := rec.task
		tasks = append(tasks, &clone)
	}
	return tasks
}

// Cancel stops a running task. The task's context will be canceled,
// and the task will transition to StatusCanceled.
// Returns an error if the task does not exist or is not running.
func (m *TaskMgr) Cancel(id string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok {
		return fmt.Errorf("subagent: task %q not found", id)
	}
	if rec.done {
		return fmt.Errorf("subagent: task %q is not running (status: %s)", id, rec.task.Status)
	}

	rec.done = true
	rec.cancel()
	now := time.Now()
	rec.task.Status = StatusCanceled
	rec.task.DoneAt = &now

	m.sendNotificationLocked(&Notification{Task: cloneTask(&rec.task)})
	m.cond.Broadcast()
	return nil
}

// Notifications returns a read-only channel that receives a Notification
// each time a task reaches a terminal state.
func (m *TaskMgr) Notifications() <-chan *Notification {
	return m.notifications
}

// HasRunning reports whether any tasks are currently in StatusRunning.
func (m *TaskMgr) HasRunning() bool {
	m.mu.Lock()
	defer m.mu.Unlock()

	for _, rec := range m.tasks {
		if !rec.done {
			return true
		}
	}
	return false
}

// WaitAllDone blocks until all registered tasks have reached a terminal state,
// or until the provided context is canceled.
func (m *TaskMgr) WaitAllDone(ctx context.Context) error {
	done := make(chan struct{})
	defer close(done)
	go func() {
		select {
		case <-ctx.Done():
			m.cond.Broadcast()
		case <-done:
		}
	}()

	m.mu.Lock()
	defer m.mu.Unlock()

	for m.hasRunningLocked() {
		if ctx.Err() != nil {
			return ctx.Err()
		}
		m.cond.Wait()
	}
	return nil
}

// Close performs graceful shutdown.
// It waits for all running tasks to complete (up to the ctx deadline),
// then cancels any remaining running tasks and closes the Notifications channel.
// After Close returns, Run will return an error.
func (m *TaskMgr) Close(ctx context.Context) error {
	_ = m.WaitAllDone(ctx)

	m.mu.Lock()
	defer m.mu.Unlock()

	m.closed = true

	for _, rec := range m.tasks {
		if !rec.done {
			rec.done = true
			rec.cancel()
			now := time.Now()
			rec.task.Status = StatusCanceled
			rec.task.DoneAt = &now
			m.sendNotificationLocked(&Notification{Task: cloneTask(&rec.task)})
		}
	}

	close(m.notifications)
	return nil
}

func (m *TaskMgr) getAgent(name string) (adk.Agent, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()

	agent, ok := m.agents[name]
	return agent, ok
}

func (m *TaskMgr) register(ctx context.Context, description string, background bool) (string, context.Context, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if m.closed {
		return "", nil, fmt.Errorf("subagent: task manager is closed")
	}

	m.seq++
	id := "t_" + strconv.FormatInt(m.seq, 10)

	taskCtx, cancel := context.WithCancel(ctx)

	rec := &taskRecord{
		task: Task{
			ID:           id,
			Description:  description,
			Status:       StatusRunning,
			RunInBackground: background,
			CreatedAt:    time.Now(),
		},
		cancel: cancel,
	}
	m.tasks[id] = rec

	return id, taskCtx, nil
}

func (m *TaskMgr) complete(id, result string) {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok || rec.done {
		return
	}

	rec.done = true
	now := time.Now()
	rec.task.Status = StatusCompleted
	rec.task.Result = result
	rec.task.DoneAt = &now

	m.sendNotificationLocked(&Notification{Task: cloneTask(&rec.task)})
	m.cond.Broadcast()
}

func (m *TaskMgr) fail(id string, err error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok || rec.done {
		return
	}

	rec.done = true
	rec.cancel()
	now := time.Now()
	rec.task.Status = StatusFailed
	if err != nil {
		rec.task.Error = err.Error()
	}
	rec.task.DoneAt = &now

	m.sendNotificationLocked(&Notification{Task: cloneTask(&rec.task)})
	m.cond.Broadcast()
}

func (m *TaskMgr) hasRunningLocked() bool {
	for _, rec := range m.tasks {
		if !rec.done {
			return true
		}
	}
	return false
}

// sendNotificationLocked sends a notification on the buffered channel.
// Must be called with m.mu held. Uses non-blocking send to avoid deadlock.
func (m *TaskMgr) sendNotificationLocked(n *Notification) {
	select {
	case m.notifications <- n:
	default:
	}
}

func cloneTask(t *Task) *Task {
	clone := *t
	return &clone
}
